name: secrets_variables
on: workflow_dispatch
jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: reading the variables
        run: |
          echo "my name is ${{ vars.name }}"
          echo "my secret is ${{ secrets.API_KEY }}"
      
  
